# Generated by Django 3.2.8 on 2021-10-22 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20211021_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='show_id',
        ),
        migrations.AddField(
            model_name='shows',
            name='playing_at',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userauth.showroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='running_movie',
            field=models.ManyToManyField(to='userauth.Movies'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
