# Generated by Django 3.2.8 on 2021-10-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_no',
            field=models.TextField(blank=True, default=''),
        ),
    ]
