# Generated by Django 3.2.8 on 2021-10-28 06:42

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_user_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_no2',
            field=mirage.fields.EncryptedCharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='card_no3',
            field=mirage.fields.EncryptedCharField(default='', max_length=255),
        ),
    ]
