# Generated by Django 3.2.8 on 2021-10-28 06:44

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_auto_20211028_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_no',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_no2',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_no3',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
