# Generated by Django 3.2.8 on 2021-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_auto_20211028_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_thru1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_thru2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_thru_y1',
            field=models.CharField(blank=True, choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '29'), ('28', '29')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_thru_y2',
            field=models.CharField(blank=True, choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '29'), ('28', '29')], default='', max_length=2),
        ),
    ]
