# Generated by Django 3.2.8 on 2021-11-09 00:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_auto_20211028_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_thru_y2',
            field=models.CharField(blank=True, choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '29'), ('29', '29')], default='', max_length=2),
        ),
        migrations.CreateModel(
            name='ScheduleMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieDate', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.movies')),
            ],
        ),
    ]
