# Generated by Django 3.2.8 on 2021-11-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0015_auto_20211109_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showDateTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulemovie',
            name='movieDate',
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='movieDate',
            field=models.ManyToManyField(to='userauth.MovieTime'),
        ),
    ]
