# Generated by Django 3.2.8 on 2021-11-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_auto_20211109_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showTimes', models.CharField(blank=True, choices=[('9.00 AM', '9.00 AM'), ('11.00 AM', '11.00 AM'), ('2.00 PM', '2.00 PM'), ('5.00 PM', '5.00 PM'), ('9.00 PM', '9.00 PM'), ('11.00 PM', '11.00 PM')], default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='movietime',
            name='showDateTime',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='movieTime',
            field=models.ManyToManyField(to='userauth.MovieShowTime'),
        ),
    ]
