# Generated by Django 3.2.8 on 2021-11-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_auto_20211109_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshowtime',
            name='showTimes',
            field=models.TimeField(),
        ),
    ]
