# Generated by Django 3.2.8 on 2021-11-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_auto_20211109_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.movies', unique=True),
        ),
    ]
