# Generated by Django 3.2.8 on 2021-11-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0020_alter_schedulemovie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemovie',
            name='PlayingTill',
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedulemovie',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.movies'),
        ),
    ]
