# Generated by Django 3.2.8 on 2021-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0022_auto_20211109_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='PlayingTill',
            field=models.DateField(blank=True, null=True),
        ),
    ]
