# Generated by Django 3.2.8 on 2021-11-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0023_alter_schedulemovie_playingtill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='showDate',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='showTimes',
        ),
    ]
