# Generated by Django 3.2.8 on 2021-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0024_auto_20211109_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promo_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
