# Generated by Django 3.2.8 on 2021-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0026_promotions_is_promo_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='seat',
        ),
        migrations.AlterField(
            model_name='promotions',
            name='is_promo_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promo_code',
            field=models.CharField(editable=models.BooleanField(default=False, editable=False), help_text='Promotion code once created is non-editable', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='numSeats',
            field=models.IntegerField(help_text='Number of seats should be a positive input'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='showroom',
            field=models.CharField(help_text='Single character theatre code', max_length=1),
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
