# Generated by Django 3.2.8 on 2021-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0027_auto_20211111_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.AlterField(
            model_name='showroom',
            name='showroom',
            field=models.CharField(help_text='Single character theatre code', max_length=1, unique=True),
        ),
    ]
