# Generated by Django 3.2.8 on 2021-11-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0028_auto_20211111_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemovie',
            name='showroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.showroom'),
            preserve_default=False,
        ),
    ]
