# Generated by Django 3.2.8 on 2021-11-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0029_schedulemovie_showroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemovie',
            name='movieTime',
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='movietime1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.movieshowtime'),
            preserve_default=False,
        ),
    ]
