# Generated by Django 3.2.8 on 2021-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0031_alter_schedulemovie_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='movietime1',
            field=models.TextField(blank=True, choices=[('7AM', '7AM'), ('9AM', '9AM'), ('11AM', '11AM'), ('1PM', '1PM'), ('3PM', '3PM'), ('5PM', '5PM'), ('7PM', '7PM'), ('9PM', '9PM'), ('11PM', '11PM')], max_length=10, null=True),
        ),
    ]
