# Generated by Django 3.2.8 on 2021-11-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0032_alter_schedulemovie_movietime1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.movies'),
        ),
    ]
