# Generated by Django 3.2.8 on 2021-11-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0033_alter_schedulemovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemovie',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.showroom'),
        ),
    ]
