# Generated by Django 3.2.8 on 2021-11-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0034_auto_20211111_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='PlayingTill',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedulemovie',
            name='movietime1',
            field=models.TextField(choices=[('7AM', '7AM'), ('9AM', '9AM'), ('11AM', '11AM'), ('1PM', '1PM'), ('3PM', '3PM'), ('5PM', '5PM'), ('7PM', '7PM'), ('9PM', '9PM'), ('11PM', '11PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulemovie',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.showroom'),
        ),
    ]
