# Generated by Django 3.2.8 on 2021-11-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0035_auto_20211111_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemovie',
            old_name='movietime1',
            new_name='MovieTime',
        ),
        migrations.RenameField(
            model_name='schedulemovie',
            old_name='PlayingTill',
            new_name='PlayingOn',
        ),
        migrations.AlterUniqueTogether(
            name='schedulemovie',
            unique_together={('showroom', 'MovieTime', 'PlayingOn')},
        ),
    ]
