# Generated by Django 3.2.8 on 2021-11-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0036_auto_20211114_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemovie',
            name='archived',
        ),
        migrations.AddField(
            model_name='movies',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
