# Generated by Django 3.2.8 on 2021-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0040_alter_schedulemovie_playingon'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
