# Generated by Django 3.2.8 on 2021-11-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0041_promotions_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='playing_at',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='running_movie',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='discount',
        ),
        migrations.AddField(
            model_name='promotions',
            name='less',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
