# Generated by Django 3.2.8 on 2021-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0042_auto_20211120_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemovie',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='ticket_adult',
            field=models.FloatField(default=7.99),
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='ticket_child',
            field=models.FloatField(default=4.99),
        ),
        migrations.AddField(
            model_name='schedulemovie',
            name='ticket_senior',
            field=models.FloatField(default=6.99),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='numSeats',
            field=models.IntegerField(default=40),
        ),
    ]
