# Generated by Django 3.2.8 on 2021-11-20 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0043_auto_20211120_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemovie',
            name='booked_seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
    ]
