# Generated by Django 3.2.8 on 2021-11-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0045_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='isBookingCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
