# Generated by Django 3.2.8 on 2021-11-21 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0046_tickets_isbookingcancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
