# Generated by Django 3.2.8 on 2021-11-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0047_tickets_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_state_01', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_02', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_03', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_04', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_05', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_06', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_07', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_08', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_09', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_10', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_11', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_12', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_13', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_14', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_15', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_16', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_17', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_18', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_19', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_20', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_21', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_22', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_23', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_24', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_25', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_26', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_27', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_28', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_29', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_30', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_31', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_32', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_33', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_34', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_35', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_36', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_37', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_38', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_39', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_40', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_41', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_42', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_43', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_44', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_45', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_46', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_47', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('seat_state_48', models.CharField(choices=[['seat', 'seat'], ['seat selected', 'seat selected'], ['seat occupied', 'seat occupied']], default='seat', max_length=15)),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.schedulemovie')),
            ],
        ),
    ]
