# Generated by Django 3.2.8 on 2021-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0048_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='seat_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
