# Generated by Django 3.2.8 on 2021-11-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0049_tickets_seat_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='isBookingCancelled',
            new_name='isBookingDone',
        ),
    ]
