# Generated by Django 3.2.8 on 2021-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0050_rename_isbookingcancelled_tickets_isbookingdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promo_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
