# Generated by Django 3.2.8 on 2021-11-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0051_alter_promotions_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='payamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticekt_cost', models.IntegerField(default=0)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('tickets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.tickets')),
            ],
        ),
    ]
