# Generated by Django 3.2.8 on 2021-11-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0052_bookings_payamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payamount',
            old_name='ticekt_cost',
            new_name='ticket_cost',
        ),
    ]
