# Generated by Django 3.2.8 on 2021-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0053_rename_ticekt_cost_payamount_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payamount',
            name='ticket_cost',
            field=models.FloatField(default=0),
        ),
    ]
