# Generated by Django 3.2.8 on 2021-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0054_alter_payamount_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='total',
            field=models.FloatField(),
        ),
    ]
