# Generated by Django 3.2.8 on 2021-11-28 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0055_alter_bookings_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bookingID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
